### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by hubertguillemain** [peterprib/node-red-contrib-loadbalance#1]
The node's title and short description (load balance to flows on remote node-red instances) are really promising, but at the moment it looks like this node takes the same approach to the existing msg-router node (https://flows.nodered.org/node/node-red-contrib-msg-router) - I'm not the author by the way.

Can you let me know how you intend to implement the load balancing to remote node-red flows, because this would be a key feature for me :)

**Comment by peterprib** [comment]
Hadn't noticed the other contribution,   On load balancing, initial thoughts were current out nodes gave this flavor however am looking at dynamically adding nodes based on template.  That is, remotes nodes register and an output node is generated along with wire to node

But my next step is it to receive messages about resource usage/availability and route based on this as a weighting.  That way when I get to next step, the remote node can send feedback on load/availability. 

Hence why I named it load balance rather than router.

**Comment by hubertguillemain** [comment]
Sounds good, I'll be following this closely 👍

**Comment by peterprib** [comment]
Have added dynamic routes but only for "http request" as template.  Didn't want to build a complex node so did it via a template.  There are some interesting limitations.  Tell me if you want a different template type.
